language: android
jdk: oraclejdk8

before_install: cd app

android:
  components:
  - build-tools-25.0.2
  - android-25
  - tools
  - platform-tools
  - extra-google-m2repository
  - extra-android-m2repository

