language: android
jdk: oraclejdk8

before_install: cd app

android:
  components:
  - tools
  - platform-tools
  - build-tools-25.0.2
  - android-25


licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
 

script: ./gradlew build check
