language: android
jdk: oraclejdk8

before_install: cd app

android:
  components:
  - tools
  - platform-tools
  - build-tools-25.0.2
  - android-25
  - extra-google-m2repository
  - extra-android-m2repository

licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'
    
notifications:
  slack: prodoteam:nUA3S3kz6rM7RVhOw4WOmc9U
  email: false
 

script: ./gradlew build check
