language: android
jdk: oraclejdk8

before_install: cd app

android:
  components:
  - tools
  - platform-tools
  - build-tools-25.0.2
  - android-25
  - extra-google-m2repository
  - extra-android-m2repository
  - sys-img-armeabi-v7a-android-25
  - sys-img-armeabi-v7a-android-17


licenses:
    - 'android-sdk-preview-license-.+'
    - 'android-sdk-license-.+'
    - 'google-gdk-license-.+'

script: ./gradlew build check
